### ISSUE TITLE
error: could not execute process `C:\Users\Jordi\AppData\Local\Android\ndk\toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64\bin/arm-linux-androideabi-gcc

### ISSUE THREAD

**Issue by JordiOfRivia** [OptimisticPeach/android_rs_base#2]

**Comment by OptimisticPeach** [comment]
Could you please provide some more information in relation to the error? Also, please don't try to make it work on windows, instead use WSL, I found that making it work on plain windows is a bit of a rabbit hole 😅 

Oh, and not to mention that because Ubuntu has a nice packaging system, it's alot easier to install the dependencies for this!

**Comment by OptimisticPeach** [comment]
I'm going to close this due to inactivity over the past 5 months.
